In [ ]:
import numpy as np

# Create a 1D array from a Python list
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

print("*"*30)

# Create a 2D array (matrix) of zeros
zeros = np.zeros((3, 3))
print(zeros)

print("*"*30)
# Create a 1D array with values ranging from 0 to 9
arr_range = np.arange(10)
print(arr_range)


[1 2 3 4 5] <class 'numpy.ndarray'>
******************************
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
******************************
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Get a slice of the array
slice_arr = arr[1:4]  # Elements from index 1 to 3
print(slice_arr)

# Access individual elements
first_element = arr[0]
print(first_element)


# Access individual elements
last_element = arr[-1]
print(last_element)

[20 30 40]
10
50


In [ ]:
arr = np.arange(12)  # Create an array with values from 0 to 11
print(arr)


print("*"*30)
# Reshape it into a 3x4 matrix
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)


print("*"*30)
# Reshape it into a 6x2 matrix
reshaped_arr = arr.reshape(6, 2)
print(reshaped_arr, type(reshaped_arr))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
******************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
******************************
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] <class 'numpy.ndarray'>


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("*"*30)
# Element-wise addition
sum_arr = arr1 + arr2
print(sum_arr)

print("*"*30)
# Element-wise multiplication
product_arr = arr1 * arr2
print(product_arr)

print("*"*30)
# Scalar multiplication (every element is multiplied by 2)
scaled_arr = arr1 * 2
print(scaled_arr)
print(arr1)


******************************
[5 7 9]
******************************
[ 4 10 18]
******************************
[2.5 5.  7.5]
[1 2 3]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("*"*30)
# Sum of all elements
sum_value = np.sum(arr)
print(sum_value)

print("*"*30)
# Mean of the elements
mean_value = np.mean(arr)
print(mean_value)

print("*"*30)
# Maximum and Minimum
max_value = np.max(arr)
min_value = np.min(arr)
print(f"Max: {max_value}, Min: {min_value}")


******************************
150
******************************
30.0
******************************
Max: 50, Min: 10


In [ ]:
# Create two 2x2 matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using np.dot or @ operator
result = np.dot(matrix1, matrix2)  # Same as: result = matrix1 @ matrix2
print(result)


[[19 22]
 [43 50]]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the matrix
transposed = np.transpose(matrix)
# Alternatively: transposed = matrix.T
print(transposed)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Generate a 2x3 array with random values between 0 and 1
random_arr = np.random.rand(2, 3)
print(random_arr)

# Generate an array with random integers between 0 and 10
random_ints = np.random.randint(0, 10, size=(9, 9))
print(random_ints)


[[0.5214519  0.05039976 0.17658338]
 [0.84801412 0.61835377 0.9802238 ]]


TypeError: rand() got an unexpected keyword argument 'size'

In [ ]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate them along axis 0 (row-wise)
concatenated = np.concatenate((arr1, arr2))
print(concatenated)


print("*"*30)
# Create two 2D arrays and concatenate along axis 1 (column-wise)
arr_2d_1 = np.array([[1, 2], [3, 4]])
arr_2d_2 = np.array([[5, 6], [7, 8]])

print("*"*30)
concatenated_2d = np.concatenate((arr_2d_1, arr_2d_2), axis=0)
print(concatenated_2d)


print("*"*30)
concatenated_2d = np.concatenate((arr_2d_1, arr_2d_2), axis=1)
print(concatenated_2d)

arr_2d_1 = np.array([[1, 2, 3], [99, 4, 5]])
arr_2d_2 = np.array([[5, 6, 7], [77, 88, 95]])

print("*"*30)
concatenated_2d = np.concatenate((arr_2d_1, arr_2d_2), axis=0)
print(concatenated_2d)


print("*"*30)
concatenated_2d = np.concatenate((arr_2d_1, arr_2d_2), axis=1)
print(concatenated_2d)


[1 2 3 4 5 6]
******************************
******************************
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
******************************
[[1 2 5 6]
 [3 4 7 8]]
******************************
[[ 1  2  3]
 [99  4  5]
 [ 5  6  7]
 [77 88 95]]
******************************
[[ 1  2  3  5  6  7]
 [99  4  5 77 88 95]]


In [ ]:

arr_2d_1 = np.array([[7,5,8], [2,4,9], [7,9,3]])
arr_2d_2 = np.array([[9,9,1], [8,2,4], [8,4,3]])

print("*"*30)
concatenated_2d = np.concatenate((arr_2d_1, arr_2d_2), axis=0)
print(concatenated_2d)



print("*"*30)
concatenated_2d = np.concatenate((arr_2d_1, arr_2d_2), axis=1)
print(concatenated_2d)

print("*"*30)
concatenated_2d = np.concatenate((arr_2d_1, arr_2d_2), axis=None)
print(concatenated_2d)


******************************
[[7 5 8]
 [2 4 9]
 [7 9 3]
 [9 9 1]
 [8 2 4]
 [8 4 3]]
******************************
[[7 5 8 9 9 1]
 [2 4 9 8 2 4]
 [7 9 3 8 4 3]]
******************************
[7 5 8 2 4 9 7 9 3 9 9 1 8 2 4 8 4 3]


In [ ]:
import numpy as np
import time

# Create large arrays/lists
size = 10**6
print(size)
python_list1 = list(range(size))
python_list2 = list(range(size))

numpy_array1 = np.arange(size)
numpy_array2 = np.arange(size)

# Timing addition using Python lists
start_time = time.time()
result_list = [x + y for x, y in zip(python_list1, python_list2)]
python_time = time.time() - start_time

# Timing addition using NumPy arrays
start_time = time.time()
result_numpy = numpy_array1 + numpy_array2
numpy_time = time.time() - start_time

# Print results
print(f"Time taken using Python lists: {python_time:.6f} seconds")
print(f"Time taken using NumPy arrays: {numpy_time:.6f} seconds")


1000000
Time taken using Python lists: 0.090840 seconds
Time taken using NumPy arrays: 0.008168 seconds


In [42]:
import numpy as np

arr = np.array([0, np.pi/2, np.pi])
print(len(arr))
# Apply sine function element-wise
sin_values = np.sin(arr)
print("Sine values:", sin_values)


cos_values = np.cos(arr)
print("Sine values:", cos_values)

# Apply exponential and square root
exp_values = np.exp(arr)
sqrt_values = np.sqrt(np.array([1, 4, 91]))

print("Exponential values:", exp_values)
print("Square root values:", sqrt_values)


3
Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Sine values: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponential values: [ 1.          4.81047738 23.14069263]
Square root values: [1.         2.         9.53939201]


In [46]:
arr = np.array([1, 2, 2, 3, 4, 4, 5, 5, 5, 5 ,5 ,5, 5])

# Find unique elements
unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)

# Find unique elements and their counts
unique_elements, counts = np.unique(arr, return_counts=True)
print(unique_elements)
print(counts)
print("Unique elements and their counts:", list(zip(unique_elements, counts)))

x, y = 8, 10

Unique elements: [1 2 3 4 5]
[1 2 3 4 5]
[1 2 1 2 7]
Unique elements and their counts: [(1, 1), (2, 2), (3, 1), (4, 2), (5, 7)]
